import streamlit as st
from groq import Groq
from pptx import Presentation
from pptx.util import Inches, Pt
import io
import urllib.parse

# --- إعدادات الصفحة ---
st.set_page_config(page_title="SwiftSlide AI | Dashboard", page_icon="🚀", layout="centered")

# --- تنسيق الواجهة (CSS) ---
st.markdown("""
    <style>
    .stApp { background-color: #0e1117; }
    .title-text { text-align: center; color: #00d4ff; font-size: 45px; font-weight: bold; }
    .unlock-box { background-color: #1e293b; padding: 20px; border-radius: 15px; border: 1px solid #3b82f6; }
    .whatsapp-btn { display: flex; align-items: center; justify-content: center; background-color: #25D366; color: white !important; padding: 12px; text-decoration: none; border-radius: 10px; font-weight: bold; margin-top: 10px; }
    </style>
""", unsafe_allow_html=True)

# --- دالة صناعة ملف البوربوينت PPTX ---
def create_pptx(text_content, topic_name):
    prs = Presentation()
    
    # سلايد العنوان الرئيسي
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = topic_name.upper()
    slide.placeholders[1].text = "Generated by SwiftSlide AI\nPremium Presentation"

    # تقسيم المحتوى إلى سلايدات
    # نفترض أن الذكاء الاصطناعي سيعطينا المحتوى مقسماً بكلمة "Slide"
    slides_data = text_content.split("Slide")
    for data in slides_data:
        if len(data).strip() > 10:
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            
            lines = data.strip().split("\n")
            # تنظيف العنوان
            title_text = lines[0].replace(":", "").replace("1", "").replace("2", "").replace("3", "").replace("4", "").replace("5", "").strip()
            slide.shapes.title.text = title_text
            
            # إضافة النقاط
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            for line in lines[1:]:
                if line.strip():
                    p = tf.add_paragraph()
                    p.text = line.strip("-*• ")
                    p.level = 0

    binary_io = io.BytesIO()
    prs.save(binary_io)
    return binary_io.getvalue()

# --- المتغيرات الأساسية ---
ADMIN_UNLOCK_CODE = "SWIFT2025" # رمز التفعيل الذي ستعطيه للزبون بعد الدفع
WHISH_NUMBER = "81950506"
MY_PHONE = "96181950506"

# --- الاتصال بـ Groq ---
api_key = st.secrets.get("GROQ_API_KEY")
if not api_key:
    st.error("Missing GROQ_API_KEY in Secrets!")
    st.stop()

client = Groq(api_key=api_key)

# --- واجهة المستخدم ---
st.markdown('<h1 class="title-text">SwiftSlide AI 🚀</h1>', unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #9ca3af;'>Create Professional PowerPoint in Seconds</p>", unsafe_allow_html=True)
st.divider()

topic = st.text_input("What is your presentation about?", placeholder="e.g. Benefits of Solar Energy")

if st.button("Generate Presentation ✨"):
    if topic:
        with st.spinner("🚀 AI is designing your slides..."):
            try:
                # طلب المحتوى من Groq
                response = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=[
                        {"role": "system", "content": "You are a professional presentation creator. Output 5 slides. For each slide start with 'Slide X: Title' then 3 bullet points."},
                        {"role": "user", "content": f"Create content for: {topic}"}
                    ]
                )
                
                content = response.choices[0].message.content
                st.session_state['content'] = content
                st.session_state['pptx_binary'] = create_pptx(content, topic)
                st.session_state['ready'] = True
                st.rerun()
            except Exception as e:
                st.error(f"Error: {e}")

# --- عرض النتائج ونظام القفل ---
if 'ready' in st.session_state:
    st.success("✅ Presentation Content Generated!")
    
    with st.expander("👁️ Preview Content"):
        st.markdown(st.session_state['content'])
    
    st.divider()
    
    # صندوق القفل
    st.markdown('<div class="unlock-box">', unsafe_allow_html=True)
    st.markdown("### 🔒 Unlock & Download PPTX File")
    st.write(f"To get the activation code, please send **$4** to Whish Money: **{WHISH_NUMBER}**")
    
    code_input = st.text_input("Enter Activation Code:", placeholder="Type code here...")
    
    if code_input == ADMIN_UNLOCK_CODE:
        st.balloons()
        st.download_button(
            label="📥 Download PowerPoint (.pptx)",
            data=st.session_state['pptx_binary'],
            file_name=f"{topic}.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            use_container_width=True
        )
    elif code_input != "":
        st.error("❌ Incorrect Code! Please contact support.")
    
    # زر الواتساب
    whatsapp_msg = f"Hello! I generated a presentation about '{topic}'. I've sent $4 to {WHISH_NUMBER}. Please send me the Activation Code!"
    url_msg = urllib.parse.quote(whatsapp_msg)
    st.markdown(f'<a href="https://wa.me/{MY_PHONE}?text={url_msg}" class="whatsapp-btn">Send Payment Proof to Admin</a>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

st.markdown("<br><p style='text-align: center; color: #4b5563; font-size: 0.8rem;'>SwiftSlide AI Lebanon © 2025</p>", unsafe_allow_html=True)
